[pytest]
python_files = *abc.py
python_functions = *sum*

markers =
    positive_test: только позитивные тесты
    auth_test: тесты на авторизацию
python_functions = test_sum_positive_nums

1.НЕ РАБОТАЕТ ФАЙЛ ini ЧТОБЫ ЗАПУСКАТЬ ОТДЕЛЬНО КАКИЕ ЛИБО ТЕСТЫ
2.ТАК ЖЕ НЕ РАЗРЕШАЕТ ПРОБЛЕМУ С МАРКИРОВКОЙ

